# TODO:
# check OS/Distro type
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html
# add zabbix repo
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html
# add repo key
# install zabbix-agent2
# configure /etc/zabbix/zabbix_agent2.conf
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/replace_module.html
# start and enable zabbix-agent2.service
# use variables and configuration/variables file

# SELinux status
# Firewall 10050

# ansible-playbook install-zabbix-agent2-on-linux.yaml -i inventory.ini --ssh-common-args='-o StrictHostKeyChecking=no' -k -v

# - hosts: all
- hosts: lviv-linux-vms
  become: yes
  gather_facts: true
  tasks:

  - name: Update ca-certificates on CentOS 7
    yum:
      name: ca-certificates
      state: latest
    when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"

  - name: Update ca-certificates on CentOS 8
    dnf:
      name: ca-certificates
      state: latest
    when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8"

  - rpm_key:
      state: present
      key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
      # rpm --import https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
      # rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'
      # rpm -e gpg-pubkey-a14fe591-578876fd

  - name: Add zabbix repo to Centos 7
    yum:
      name: https://repo.zabbix.com/zabbix/5.4/rhel/7/x86_64/zabbix-release-5.4-1.el7.noarch.rpm
      state: present
    when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"

  - name: Add zabbix repo to Centos 8
    dnf:
      name: https://repo.zabbix.com/zabbix/5.4/rhel/8/x86_64/zabbix-release-5.4-1.el8.noarch.rpm
      state: present
    when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8"

  - name: Install zabbix-agent2 to Centos
    yum:
      name: "zabbix-agent2"
      state: present
    when: ansible_facts['distribution'] == "CentOS"

  - name: Set Server in zabbix_agent2.conf
    ansible.builtin.replace:
      path: /etc/zabbix/zabbix_agent2.conf
      regexp: '^Server=127.*'
      replace: 'Server=zabbix.mydomain.loc'

  - name: Set ServerActive in zabbix-agent2.conf
    ansible.builtin.replace:
      path: /etc/zabbix/zabbix_agent2.conf
      regexp: '^ServerActive=127.*'
      replace: 'ServerActive=zabbix.mydomain.loc'

  - name: Set hostname in zabbix-agent2.conf
    ansible.builtin.replace:
      path: /etc/zabbix/zabbix_agent2.conf
      regexp: '^Hostname=.*'
      replace: "Hostname={{inventory_hostname}}"
      # replace: "Hostname={{ansible_fqdn}}"
      # replace: "Hostname={{ansible_hostname}}"

  - name: Start and enable zabbix-agent2.service
    ansible.builtin.systemd:
      name: zabbix-agent2
      state: restarted
      enabled: yes
      masked: no
